- name: Install docker
  shell: curl -fsSL https://get.docker.com/ | sh

- name: Install Docker Compose
  shell: curl -L https://github.com/docker/compose/releases/download/{{ COMPOSE_VERSION }}/docker-compose-`uname -s`-`uname -m` > /usr/bin/docker-compose

- name: Change Docker Compose execute permissions
  file: path="/usr/bin/docker-compose" mode="u+x"

- name: Restart Docker Deamon
  service: name=docker state=started enabled=yes

- name: update /usr/lib/systemd/system/docker.service
  ini_file: dest=/usr/lib/systemd/system/docker.service
            section=Service
            option=ExecStart
            value="/usr/bin/dockerd $DOCKER_OPTS"

- name: update /usr/lib/systemd/system/docker.service
  ini_file: dest=/usr/lib/systemd/system/docker.service
            section=Service
            option=Environment
            no_extra_spaces=true

- name: Reload docker
  systemd: name=docker
           daemon_reload=yes
           state=reloaded

- name: Restart docker
  systemd: name=docker
           state=restarted
